export const routerPath = {
   HOME: '/',
   LOGIN: '/login',
   REGISTER: '/register',
   AUTH: '/auth',
   PLAY: '/play',
   DASHBOARD: '/dashboard',
   EMPLOYEE_DETAIL: '/employee-detail/:employeeID',
   MANAGE_CHATBOT: '/manage-flow',
   MANAGE_CHATBOT_BY_ID: '/manage-flow/:id',
   MANAGE_CHANEL: '/manage-chanel',
   TRAINING: '/training',
   NOT_FOUND: '/notfound',
   ANY: '*',
};
